BITMAKER-2117: Configure WebPack to use Micro-frontend
bitmakerla/estela pull request #100
Opened 2022-11-11 16:23 UTC by JoseArmandoChavezQuijahuaman

# Description

Add env variables and define a standard to use Micro-frontend, configure estela-web to be able to use Module-Federation and use external code.

# Issue

* [Issue ID](https://tasks.bitmaker.dev/issues/2117).

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines of this project.
- [x] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [x] New and existing tests pass locally with my changes.
- [x] If this change is a core feature, I have added thorough tests.
- [x] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [x] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-11-13 18:02 UTC, Adriana618 requested changes
Maybe `defaultComponents` is a better name than`fakeComponents`

2022-11-15 13:39 UTC, JoseArmandoChavezQuijahuaman commented
@Adriana618 , @rodp63, It's ready to review.

2022-11-16 01:36 UTC, rodp63 commented on docs/estela/installation/micro-frontends.md
> +parent: Installation
The parent should be the section `Web`, not `Installation`.

2022-11-16 01:37 UTC, rodp63 commented on docs/estela/installation/micro-frontends.md
> +estela allows the use of Micro-Frontends only in the user dropdown. This is achieved with the use of [Module Federation](https://webpack.js.org/concepts/module-federation/).
We should give more context about the aim of using micro frontends. Why are they important? How this helps estela?

2022-11-16 01:40 UTC, rodp63 commented on docs/estela/installation/micro-frontends.md
> +    // example
A real example would be more descriptive, do we have a demo micro frontend? The full pipeline should be described, it could be another PR

2022-11-17 19:11 UTC, rodp63 approved these changes
Looks good, don’t forget to create the _Getting Started Guide_ in another PR

2022-11-20 01:29 UTC, merged