BITMAKER-2142 estela-web: Implement "In Projects/Scheduled Jobs"
bitmakerla/estela pull request #106
Opened 2022-11-18 18:56 UTC by raymond1242

# Description

estela-web: Implement "In Projects/Scheduled Jobs"

# Issue

https://tasks.bitmaker.dev/issues/2142

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-11-24 03:32 UTC, raymond1242 commented
@Adriana618 This is ready to review

2022-11-29 12:49 UTC, Adriana618 requested changes

2022-11-29 12:49 UTC, Adriana618 commented on estela-web/src/components/CronJobDetailPage/index.tsx
> +                                            </Text> */}
Remove all comments.

2022-11-29 12:49 UTC, Adriana618 commented on estela-web/src/components/CronJobDetailPage/index.tsx
> +                    weekDays[moment().day() % 7] = true;
It would be better to run a separate query for each type of Status.

2022-11-29 18:02 UTC, raymond1242 commented on estela-web/src/components/CronJobDetailPage/index.tsx
> +                                            </Text> */}
Done

2022-11-29 18:40 UTC, raymond1242 commented
@Adriana618 I fixed the comment you did

2022-11-29 23:01 UTC, Adriana618 approved these changes
Looks good.

2022-11-30 00:30 UTC, merged