BITMAKER-2209 estela-web: Connect Resources Consumption in Dashboard component
bitmakerla/estela pull request #113
Opened 2022-12-05 20:43 UTC by raymond1242

# Description

estela-web: Connect Resources Consumption in Dashboard component

# Issue

https://tasks.bitmaker.dev/issues/2209

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-12-05 23:01 UTC, raymond1242 commented
@Adriana618 This PR is ready for review

2022-12-07 03:47 UTC, Adriana618 requested changes

2022-12-07 16:28 UTC, raymond1242 commented on estela-web/src/components/ProjectDashboardPage/index.tsx
> +                                                    )}
Done

2022-12-07 17:09 UTC, raymond1242 commented
@Adriana618 This PR is issues fixed

2022-12-12 16:07 UTC, raymond1242 commented
@Adriana618 This PR is ready for review

2022-12-12 23:14 UTC, Adriana618 approved these changes
Looks good

2022-12-12 23:35 UTC, merged