Bitmaker 2101 estela-web: Implement "Jobs/Overview" mockup
bitmakerla/estela pull request #116
Opened 2022-12-11 19:36 UTC by webtaken

# Description

Implement "Jobs/Overview" mockup.

# Issue

* https://tasks.bitmaker.dev/issues/2101.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [x] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-12-14 21:21 UTC, raymond1242 commented on estela-web/src/components/JobDetailPage/index.tsx
> +            // this.getStats("1");
Delete comments

2022-12-14 21:22 UTC, raymond1242 commented on estela-web/src/components/JobDetailPage/index.tsx
> +                                                    key: "2",
Delete comments

2022-12-14 21:24 UTC, raymond1242 commented on estela-web/src/components/JobDetailPage/index.tsx
> +                        <div className="grid w-full h-1/2 place-content-center">
Instead of `div` tag, use `Content`

2022-12-14 21:28 UTC, raymond1242 commented on estela-web/src/components/JobDetailPage/index.tsx
> +        const storageDecimalPercentage = dataStatus !== "DELETED" ? (totalResponseBytes || 0) * 1e-9 : 0;
Some cases the storage data is really short, and in the circle doesn't show anything. You could display the size even in megabytes to know there is a consume by the job

2022-12-14 21:28 UTC, raymond1242 requested changes
Check the comments pls

2022-12-14 21:33 UTC, raymond1242 commented on estela-web/src/components/JobDetailPage/index.tsx
> +                                <Text className="text-estela-black-medium text-xs">of project (disabled)</Text>
You can disable the whole `Col` tag, also reduce the opacity to show that feature disabled

2022-12-15 03:33 UTC, webtaken reviewed
Added the required changes.

2022-12-15 17:04 UTC, webtaken reviewed
Changed the opacity and enhancement in the circular percentage feature part.

2022-12-15 17:41 UTC, webtaken reviewed
Ok required changes done.

2022-12-15 18:16 UTC, raymond1242 approved these changes
Good Job!

2022-12-15 18:17 UTC, merged