BITMAKER-2625 estela: Propose Model and implementation for Activity Menu
bitmakerla/estela pull request #160
Opened 2023-03-21 15:38 UTC by raymond1242

# Description

Currently, there is a disable Activity Menu on estela platform. This menu allows users to watch every process executed on estela. It view records the activity for the whole project

# Issue

[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/2625)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2023-03-24 22:45 UTC, raymond1242 commented
@Adriana618 This PR is ready for review

2023-04-12 03:43 UTC, raymond1242 commented
@emegona This PR is conflicts free

2023-05-02 05:13 UTC, mgonnav requested changes
I think these changes are extremely similar, not to same pretty much equal, to what was done for the Notifications stuff. In that case, let's hold on on this PR until the notifications changes are merged, make changes here on top of that. I think there's a lot we can refactor betweent he two. Let me know what you think.

2023-05-02 05:13 UTC, mgonnav commented on estela-api/core/models.py
> +        help_text="Project to which the activity corresponds.",
Let's change this to `Project where the activity was performed.`

2023-05-02 05:13 UTC, mgonnav commented on estela-api/core/models.py
> +        auto_now_add=True, editable=False, help_text="Activity creation date."
Let's use `Date when the activity was performed.`. It's more descriptive of what it refers to.

2023-05-02 05:13 UTC, mgonnav commented on estela-api/api/mixins.py
> +class ActivityHandler(viewsets.GenericViewSet):
Please change this to `class ActivityHandlerMixin:`. Inheriting from `viewsets.GenericViewSet` should not be needed here. Remember to change all the occurrences of the name. Let me know if there are any problems with this change.

2023-05-18 20:27 UTC, raymond1242 commented
It's correct! Handler and database querys arrñe similar. I'll finish with notifications first

2023-06-26 23:41 UTC, raymond1242 commented
@mgonnav This PR is ready for review

2023-07-11 12:52 UTC, mgonnav approved these changes

2023-07-11 12:56 UTC, merged