BITMAKER-2589: Change password mockup & integration with backend
bitmakerla/estela pull request #161
Opened 2023-03-22 00:05 UTC by reqhiem

# Description

Just now, we don't support changing passwords for users. Recently, endpoints to do that were implemented, so it is necessary to implement the change/reset password mockup and integrate it with the backend.
Acceptance Criteria:
 - Implement Change password mockup
 - Integrate Change password endpoints and frontend page.

# Issue

https://tasks.bitmaker.dev/issues/2589

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2023-03-27 02:25 UTC, emegona requested changes
- The changes do not conform to the mockups. There is no `forgot your password?` button in the login.
- I saw a `Change password` section in the account settings, but it seems to work more like a `reset password` rather than a `change password`.
- I could not get it to work anyways. Please let me know if I'm missing something or if we need to discuss it. Thanks.

2023-03-27 02:25 UTC, emegona commented on estela-api/api/views/auth.py
>          except Exception:
The message in case of error should be `"...sending the password reset email."` rather than `"... sending the verification email."`.

2023-03-27 02:25 UTC, emegona commented on estela-api/api/views/auth.py
> +            raise UserNotFoundError({
The `UserNotFoundError` class already contains an error detail attribute. Using `raise UserNotFoundError()` should suffice. If that's the case, please change all the instances where we do this.

2023-03-27 02:25 UTC, emegona commented on estela-api/api/views/auth.py
> +        email = serializer.validated_data['email']
Please format the code using black.

2023-04-01 20:53 UTC, reqhiem commented
@emegona this PR is ready to review

2023-04-10 23:49 UTC, emegona approved these changes

2023-04-10 23:54 UTC, merged