BITMAKER-1828 Improve guide of web application structure
bitmakerla/estela pull request #41
Opened 2022-06-30 03:34 UTC by raymond1242

We currently have a significantly reduced and short description of the Web module for Estela. We should improve it so new devs can better grasp how the project is structured and things are managed.

Completion criteria:
- Provide a more detailed description of the Estela Web module (structure, tools, etc).

2022-06-30 03:38 UTC, raymond1242 commented
@mgonnav could you please review this PR, belong ticker : https://tasks.bitmaker.dev/issues/1828?issue_count=5&issue_position=3&next_issue_id=1766&prev_issue_id=1840

2022-07-02 16:57 UTC, mgonnav requested changes
We should provide a more detailed description of the project. Please provide a description of **how the project is structured and things are managed** (i.e., talk about how we manage components, assets, routes, services, etc.). It might be good to see how other projects detail this.

These changes should be added to the docs and have something more general in this README. Take the time needed to understand and give a detailed description of the web project.

2022-07-02 16:57 UTC, mgonnav commented on estela-web/README.md
> +![CI](https://github.com/eslint/eslint/workflows/CI/badge.svg)
I think we can get rid of these badges. There is a specific ticket to define this stuff for the whole project.

2022-07-02 16:57 UTC, mgonnav commented on estela-web/README.md
> +The module allows users to **CREATE**, **UPDATE** and **DELETE** information and data collected from your spiders. Similar to [estela-cli](https://github.com/bitmakerla/estela-cli) but, with an inter
I think we can be more direct by saying "This module allows users to **manage their scraping projects** and data collected from their spiders. This is a **graphical alternative** to `estela-cli`."

2022-07-02 16:57 UTC, mgonnav commented on estela-web/README.md
> +    </a></span>[**TypeScript**](https://www.typescriptlang.org) A Strongly **Typed** Programming Language
I think it should suffice to mention these and not give them so much space here. These are just the tools we use.

2022-07-22 15:07 UTC, raymond1242 commented
@mgonnav could you please check this last commit

2022-07-27 15:33 UTC, mgonnav approved these changes
I've proofread the docs and made some fixes. I think we can merge this 👍🏻

2022-07-27 15:42 UTC, merged