BITMAKER-1930: Add api parameter descriptions
bitmakerla/estela pull request #53
Opened 2022-07-23 22:44 UTC by rodp63

# Description

_We must ensure that every serializer field is well specified and follows the same format_.

# Issue

* _https://tasks.bitmaker.dev/issues/1930_.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines of this project.
- [x] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [x] New and existing tests pass locally with my changes.
- [x] If this change is a core feature, I have added thorough tests.
- [x] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [x] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-07-23 22:46 UTC, rodp63 commented
@mgonnav to merge this PR we need to merge #51 first.

2022-07-25 23:00 UTC, mgonnav requested changes
Looks good. However, there are still some fields that do not have descriptions like the field in the Response for `api_projects_spiders_jobs_list`, `api_projects_spiders_cronjobs_list `, `api_projects_deploys_list`,  `api_projects_deploys_list`.

Also, the fields `pid`, `sid`, and `jid` seem not to have a description for most of their appearances. Do you think we can add these quickly and effectively? We could specify what they are in the beginning or in a general file to make it quick.

2022-07-25 23:00 UTC, mgonnav commented on docs/estela/api/endpoints.html
>  <!DOCTYPE html>
Maybe we should remove this file since it is generated on each deployment.

2022-07-25 23:00 UTC, mgonnav commented on estela-api/api/serializers/project.py
> +        read_only=True, help_text="A uuid identifying this project."
Please use UUID uppercase.

2022-08-01 23:27 UTC, mgonnav commented on estela-api/api/mixins.py
> +    def get_paginated_response_schema(self, schema):
@rodp63 I think this is not having any effects on the final endpoint docs. If this is the case, let's just remove this.

2022-08-02 02:18 UTC, mgonnav approved these changes

2022-08-02 03:59 UTC, merged