Create CONTRIBUTING.md
bitmakerla/estela pull request #75
Opened 2022-09-22 17:06 UTC by raymond1242

# Description

Help estela repo improve compared to the community standards

# Issue

https://tasks.bitmaker.dev/issues/1909

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-09-23 01:38 UTC, Adriana618 requested changes
Maybe you can check this [guide](https://mozillascience.github.io/working-open-workshop/contributing/) about to create a CONTRIBUTING.md, for example give _rewards_ for contribute or fork is a good way to encourage people to contribute.

2022-09-23 01:38 UTC, Adriana618 commented on CONTRIBUTING.md
> +
Link doesn't work

2022-09-23 01:38 UTC, Adriana618 commented on CONTRIBUTING.md
> +This document was adapted from the open-source contribution guidelines for [Facebook's Draft](https://github.com/facebook/draft-js/blob/a9316a723f9e918afde44dea68b5f9f39b7d9b00/CONTRIBUTING.md)
Link doesn't work.

2022-09-23 01:38 UTC, Adriana618 commented on CONTRIBUTING.md
> +2. If you've added code that should be tested, add tests.
do We have a structure for tests? 
In what file or folder the contributors add the tests?
What is the approach to make test?
This and other questions needs to be answered.

2022-09-23 01:38 UTC, Adriana618 commented on CONTRIBUTING.md
> +4. Ensure the test suite passes.
How they update the documentation?
We need to define steps for this.

2022-09-29 20:39 UTC, raymond1242 commented
@Adriana618 Could you check this PR pls

2022-09-30 23:40 UTC, essiocolom approved these changes

2022-10-01 00:00 UTC, Adriana618 approved these changes

2022-10-01 00:00 UTC, Adriana618 commented on CONTRIBUTING.md
> +
I don't know if this is the best way to keep code documented.

2022-10-01 06:20 UTC, merged