BITMAKER-2057 New Login & Register frontend implemented
bitmakerla/estela pull request #78
Opened 2022-09-28 15:52 UTC by raymond1242

# Description

estela Frontend new design implementation Login

# Issue

https://tasks.bitmaker.dev/issues/2057?tab=time_entries

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-09-28 15:54 UTC, raymond1242 commented
@Adriana618 Could you check this PR. I think is done!

2022-09-28 22:35 UTC, raymond1242 commented
@Adriana618 Now it's ready

2022-09-29 20:40 UTC, raymond1242 commented
@Adriana618 Could you review this last commit pls

2022-10-03 23:04 UTC, Adriana618 requested changes
Looks good, just I think we need to center the view. Both, in login and register.

2022-10-18 14:29 UTC, raymond1242 commented
@Adriana618 Now its centered. Done!

2022-10-19 15:45 UTC, Adriana618 requested changes

2022-10-19 15:45 UTC, Adriana618 commented on estela-web/src/components/LoginPage/index.tsx
> +                            >
Don't hardcode colors, instead create a class in a .scss file

2022-10-20 16:48 UTC, Adriana618 approved these changes

2022-10-20 19:29 UTC, merged