BITMAKER-2067 estela Sidebar & Navbar new design implementation
bitmakerla/estela pull request #80
Opened 2022-10-04 16:09 UTC by raymond1242

# Description

estela Sidebar & Navbar new design implementation

# Issue

https://tasks.bitmaker.dev/issues/2067?tab=time_entries

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-10-04 16:12 UTC, eLRuLL commented on estela-web/src/components/ProjectListPage/index.tsx
> +                <Layout className="bg-[#FBFCFD]">
@raymond1242 I would prefer for this to be on a css file, because it makes it very restrictive to add it directly inside the code.

2022-10-04 16:23 UTC, eLRuLL requested changes

2022-10-04 16:23 UTC, eLRuLL commented on estela-web/src/shared/header/index.tsx
> +                    {/* <Col className="">
no comments please

2022-10-04 16:23 UTC, eLRuLL commented on estela-web/src/shared/header/index.tsx
> +                    <Col className="flex text-[#4D47C3]">
@raymond1242 if you have been doing this in several other places, even in already merged PRs, please fix that. This is not the way to determine "colors" for the entire site.

Colors and important styles should be determined in a global css file, and the respective tags should be adding those classnames

2022-10-15 14:06 UTC, raymond1242 commented
I think is now done. Could you check this PR @eLRuLL @Adriana618

2022-10-19 13:12 UTC, JoseArmandoChavezQuijahuaman reviewed
The Submenu SandBox text is a different color according to the mockup. Only that would be missing and it would be ready for the merge. Good job.

2022-10-20 14:08 UTC, raymond1242 commented
@JoseArmandoChavezQuijahuaman @Adriana618 Please review this PR. It's done!

2022-10-20 14:13 UTC, merged