BITMAKER-2086: Integrate estela with Webpack
bitmakerla/estela pull request #94
Opened 2022-10-22 19:37 UTC by JoseArmandoChavezQuijahuaman

# Description

Modify estela to use webpack and restructure the app.

# Issue

* _Github Issue ID_.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-11-01 19:10 UTC, JoseArmandoChavezQuijahuaman commented
@rodp63 I think it's ready to review.

2022-11-02 20:14 UTC, rodp63 requested changes

2022-11-02 20:14 UTC, rodp63 commented on estela-web/package.json
> +    "start:live": "webpack serve --open --mode development --live-reload --hot",
We have a `build` script in production mode, do we need a `start` script with the production flag as well?

2022-11-02 20:14 UTC, rodp63 commented on estela-web/src/custum.d.ts
> +    const content: any;
Please fix this GitHub warning

2022-11-03 22:43 UTC, JoseArmandoChavezQuijahuaman commented on estela-web/src/custum.d.ts
> +    const content: any;
Fixed up

2022-11-05 01:24 UTC, rodp63 approved these changes
Looks good 👍

2022-11-05 01:25 UTC, merged