BITMAKER-2100 estela-web: Implement "In Projects/Scheduled Jobs"
bitmakerla/estela pull request #95
Opened 2022-10-27 17:06 UTC by raymond1242

# Description

estela-web: Implement "In Projects/Scheduled Jobs" mockup

# Issue

https://tasks.bitmaker.dev/issues/2100

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-11-09 19:08 UTC, raymond1242 commented
@Adriana618 Could you review this PR pls
https://tasks.bitmaker.dev/issues/2100

2022-11-14 19:01 UTC, Adriana618 requested changes
What is the difference between this PR and this:https://github.com/bitmakerla/estela/pull/101?

2022-11-14 23:45 UTC, raymond1242 commented
@Adriana618 The PR [#101](https://github.com/bitmakerla/estela/pull/101) add role field on ProjectList component. And this PR is about styling ProjectCronjobList component, algo Cronjob Create component. Are very different

2022-11-14 23:53 UTC, raymond1242 commented
Rebase with main branch

2022-11-15 18:35 UTC, Adriana618 approved these changes
Looks good.

2022-11-15 18:35 UTC, Adriana618 commented on estela-web/src/components/ProjectListPage/index.tsx
> +            this.setState({ projects: [...projectData], count: data.count, current: data.current, loaded: true });
Probably you have conflict with this PR https://github.com/bitmakerla/estela/pull/101 if you merge both.

2022-11-15 20:22 UTC, merged