Bitmaker 2079
bitmakerla/estela pull request #97
Opened 2022-10-29 02:11 UTC by reqhiem

# Description

Implement "In Project/ Spiders" mockup.

# Issue

https://tasks.bitmaker.dev/issues/2079

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [ ] New and existing tests pass locally with my changes.
- [ ] If this change is a core feature, I have added thorough tests.
- [ ] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [ ] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

2022-11-02 16:29 UTC, raymond1242 commented on estela-web/src/components/SpiderListPage/index.tsx
> +import { Col, Layout, Row, List, Pagination, Typography, Button, Space, Table, Tag } from "antd";
Remove unused imports

2022-11-02 16:29 UTC, raymond1242 commented on estela-web/src/components/SpiderListPage/index.tsx
> +import React, { Component, Fragment, ReactElement } from "react";
Remove unused imports

2022-11-02 16:30 UTC, raymond1242 commented on estela-web/src/components/SpiderListPage/index.tsx
> +import { PlusOutlined } from "@ant-design/icons";
There is an already custom Icon for this import, review assets/icon folder

2022-11-02 16:31 UTC, raymond1242 requested changes
Please check the comments

2022-11-02 20:06 UTC, reqhiem commented
I solved the observations

2022-11-09 20:11 UTC, raymond1242 commented on estela-web/src/components/SpiderListPage/index.tsx
>  const { Title } = Typography;
This import is unused

2022-11-09 20:18 UTC, raymond1242 requested changes
Last observations to fix

2022-11-14 23:40 UTC, raymond1242 commented on estela-web/src/components/NotificationsInboxPage/styles.scss
> +// }
Delete comments

2022-11-14 23:40 UTC, raymond1242 commented on estela-web/src/components/NotificationsSettingsPage/styles.scss
> +// }
Delete comments

2022-11-14 23:41 UTC, raymond1242 commented on estela-web/src/services/api/generated-api/models/Spider.ts
> +    jobs?: number;
Don't add fields on files generated

2022-11-14 23:41 UTC, raymond1242 requested changes
Check and fix the comments

2022-11-29 00:09 UTC, reqhiem commented
@raymond1242 it's ready to review

2022-11-29 22:12 UTC, raymond1242 approved these changes
Good Job! It's ready to merge

2022-11-29 22:12 UTC, raymond1242 commented
@reqhiem When you clicked merge. make sure you select `Squash and Merge` option

2022-12-04 13:45 UTC, merged